### ISSUE TITLE
Different color and alignment for sent versus received messages (Chat Bubbles UX)

### ISSUE THREAD

**Issue by jdean65** [RocketChat/feature-requests#114]
**Problem:**
A sent versus received message is not delineated clearly enough in UI

**Describe the solution you'd like**
Different coloring for a sent versus received message.  Also, sent messages are aligned right in the chat window, received messages aligned left.  This is similar to the UX of whatsapp and fb messenger.   

**Describe alternatives you've considered**
Alternative is current user interface.

**Additional context**

![Screenshot_20190512-114737](https://user-images.githubusercontent.com/159204/57586524-eb742d80-74ab-11e9-9dcf-37fd407a29a5.png)

This capability received 10 votes in the now deprecated rocket.chat #features list.

**Comment by reetp** [comment]
There are a number of Issues on this type of subject.

eg
https://github.com/RocketChat/Rocket.Chat/issues/10863
https://github.com/RocketChat/Rocket.Chat/issues/10308
https://github.com/RocketChat/Rocket.Chat/issues/9681

Please have a good search and read to understand some of the background to the UI

**Comment by reetp** [comment]
This is linked as well
https://github.com/RocketChat/Rocket.Chat/pull/14892

**Comment by sergeblr** [comment]
Hello everybody, so what now with alignment of messages?

**Comment by reetp** [comment]
Related:

https://github.com/RocketChat/Rocket.Chat/issues/12343

**Comment by ankar84** [comment]
Good improvement for UI\UX

**Comment by eltrentin** [comment]
+1

**Comment by ice6** [comment]
I hope this can be helpful for the web ui

https://gist.github.com/ice6/b1977b11e68686974d737ea082ec278b

**Comment by lawipac** [comment]
@ice6 it no longer works in 6.2.*  new css is needed.  I wish I can develop one someday in the furture.

**Comment by tyroneyeh** [comment]
Try this custom CSS 

Workspace -> Settings -> Layout -> Custom CSS
```css
.rcx-message[data-own="true"] {
  justify-self: end;
}
.rcx-message[data-own="true"] * {
  align-self: end;
  margin-bottom: auto;
}
.rcx-message[data-own="true"] .rcx-message-container--left {
  order: 2; 
}
```
