### ISSUE TITLE
Ability to disable message "reporting" feature

### ISSUE THREAD

**Issue by frdmn** [RocketChat/feature-requests#158]
**Is your feature request related to a problem? Please describe.**

Currently there is no (proper) way to hide or disable the "Reporting" feature when opening the context menu of a certain message.

The only possible workaround right now is to use custom CSS to hide it, which doesn't apply to non Electron/web-based versions of Rocket.Chat:

```css
li[data-id="report-message"] {
    display: none;
}
```

**Describe the solution you'd like**

An option to toggle the reporting feature in the Administration UI.

**Comment by reetp** [comment]
Be handy if it actually did something ;-)

**Comment by florian-bellencontre** [comment]
+1 for this feature

**Comment by frostbtn** [comment]
As of v6.6 this custom css does the trick for Electron-based clients: 
```css
li#report-message {
    display: none;
}
```

Mobile clients still see the option.

**Comment by frostbtn** [comment]
Relentless! 
Since 6.7:
```css
div[data-qa-type="message-action-menu"]  label[data-key="report-message"] {
    display: none;
}
```
