### ISSUE TITLE
Initial Setup Wizard

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/feature-requests#778]
Some config options are too important to be left for later. We should have a way to mark some settings as part of of the _Setup Wizard_ so the admin will have to complete the before using the system for the first time.

**Comment by fralau** [comment]
Upon reboot of the server, the wizard accidentally restarted and it seems that the configuration has been broken. Is there ANY way to save the configuration, or anything from it (messages, etc.)?

**Comment by ChrisJBurns** [comment]
Is there a way to completely automate the setup-wizard? The manual task is a bit annoying. We install via Helm so would be great if we could get all of the setup-wizard stuff sorted before we even go to the applicaiton.

**Comment by cleric28** [comment]
> Is there a way to completely automate the setup-wizard? The manual task is a bit annoying. We install via Helm so would be great if we could get all of the setup-wizard stuff sorted before we even go to the applicaiton.

I am also currently looking for a way to do this. Is this doable through RocketChat's REST API?

**Comment by ChrisJBurns** [comment]
The best I've got is specifying the below in my Flux release for RocketChat

```yaml
    extraEnv: |
      - name: USE_NATIVE_OPLOG
        value: "true"
      - name: OVERWRITE_SETTING_Show_Setup_Wizard
        value: "completed"
      - name: ADMIN_USERNAME
        value: "EXAMPLE"
      - name: ADMIN_PASS
        value: "EXAMPLE"
      - name: ADMIN_EMAIL
        value: "EXAMPLE"
      - name: Accounts_OAuth_Custom_Keycloak
        value: "true"
      - name: Accounts_OAuth_Custom_Keycloak_url
        value: "EXAMPLE"
```
